apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apa000dep
spec:
  selector: 
    matchLabels: 
      app: app000kube
  replicas: 3
  template: 
    metadata: 
      labels:
        app: app000kube
    spec:
      containers:
        - name: apa000ex91
          image: httpd
          ports:
            - containerPort: 80