apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      test: svc
  template:
    metadata:
      labels:
        test: svc
    spec:
      containers:
        - name: ipnginx
          image: rapa1.iptime.org:5000/ipnginx