apiVersion: v1
kind: Service
metadata:
  name: ip-svc
spec:
  selector:
    test: svc
  ports:
    - name: http
      protocol: TCP
      nodePort: 30100
      port: 80
      targetPort: 80
  type: NodePort