apiVersion: v1
kind: Service
metadata:
  name: np-rep-svc
spec:
  selector:
    app: hnginx
  ports:
    - name: http
      protocol: TCP
      nodePort: 32767
      port: 80
      targetPort: 80
  type: NodePort