apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #유지
  nfs:
    path: /shared/pv1
    server: 192.168.0.210 #본인 마스터노드(/shared폴더가 있는 서버)의 주소
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #유지
  nfs:
    path: /shared/pv2
    server: 192.168.0.210 #본인 마스터노드(/shared폴더가 있는 서버)의 주소
    readOnly: false