server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lango
    driver-class-name: org.mariadb.jdbc.Driver
    username: guest1
    password: guest1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
  cache: false

  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Documents\study\data
      max-request-size: 30MB
      max-file-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9fd05402c7da1ca5187533944ef3e048
            client-secret: iGRYXWSJ9MuJCHcCZn5s9xCYIcpZUGuE
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  lango:
    upload:
      path: C:\Users\user\Documents\study\data