server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lango
    driver-class-name: org.mariadb.jdbc.Driver
    username: guest1
    password: guest1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
  cache: false

  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Documents\study\data
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  lango:
    upload:
      path: C:\Users\user\Documents\study\data