server:
  port: 80

# DB ????
spring:
  datasource:
    # mariadb ????
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/lango
    # oracle ????
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: oracle

# JPA ?? ??
# Entity? ??? ???? ?? ??? ??? ????.
#   create(?? ??? ??? ?? ??)
#   create-drop(?? ??? ???? ??? ??)
#   update(???? ??)
#   validate(??? ??)
#   none(???? ??)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # ?? ?? ???? ????? ??
        show_sql: true # SQL ??? ???? ??

# ?? ?? ??
# ???? ?? ???? ?, ?? ?????.
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
